title: "🔭 What I'm working on"
items:
  - "🛡️ Building **A.I.R.S** — Ai integrated SIEM solution for SMEs(small and medium-sized Enterprises )"
  - "🔍 Actively researching **Web, API, and Cloud Security** through bug bounty programs on Bugcrowd and HackerOne."
  - "🧠 Building **Cyber Security tools** to automate reconnaissance, vulnerability discovery, and security testing workflows."
  - "🎯 Enhancing **secure software development** by combining modern web technologies with offensive security research."

