title: "Nihar Sakhreliya"
subtitle: "Full Stack Developer"
website: "https://github.com/Sakhreliya-Nihar"
address: "kamrej,surat, Gujarat, India"
contact:
  email: "niharsakhreliya4@gmail.com"
  linkedin: "https://www.linkedin.com/in/nihar-sakhreliya/"
quote: "Kindness always come back in the ways we don't expect."
quote_author: "Nihar" 