title: "🧰 Tech Stack"
categories:
  Languages: "JavaScript, Python, Bash, Html, Css, Java"
  Cyber Security: "VAPT/WAPT, Web, API, Network Security, AD and Think client pentesting, OWASP Top 10,  Bug Bounty, OSINT"
  Tools: "Burp Suite Pro, Metasploit, Nmap, SQLMap, Hydra, Shodan, Censys, Amass, Nessus, Nuclei, Virustotal, URLScan, Wireshark, Splunk, John the Ripper"
  Frontend: "React, Tailwind CSS"
  Backend: "Nodejs, SpringBoot, GraphQL, REST"
  Database: "MongoDB, MySQL"
  Testing: "Jest, Postman" 